import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('./worker/index.js',import.meta.url),'utf8').replace('import { connect } from "cloudflare:sockets";','').replace('export default {','globalThis.worker={');
let queries=[];
const server=vm.createContext({URL,Response,Request,AbortController,setTimeout,clearTimeout,fetch:async url=>{const q=new URL(url).searchParams;queries.push([q.get('name'),q.get('type')]);return Response.json({Status:0,Answer:[{type:12,TTL:60,data:'dns.google.'}]});}});vm.runInContext(source,server);
assert.equal(server.reverseDnsName('8.8.8.8'),'8.8.8.8.in-addr.arpa');
assert.equal(server.reverseDnsName('2001:4860:4860::8888').split('.').length,34);
assert.equal(server.reverseDnsName('2001:4860:4860::8888'),server.reverseDnsName('2001:4860:4860:0:0:0:0:8888'));
assert.throws(()=>server.reverseDnsName('999.1.1.1'));assert.throws(()=>server.reverseDnsName('example.com'));
const request=ips=>new Request('https://dns.example/api/lookup?name=example.com&mode=ptr',{method:'POST',body:JSON.stringify({ips})});
assert.equal((await server.worker.fetch(request(Array(21).fill('8.8.8.8')))).status,400);
const result=await (await server.worker.fetch(request(['8.8.8.8','8.8.8.8']))).json();assert.equal(queries.length,1);assert.equal(queries[0][1],'PTR');assert.equal(result.checks[0].answers[0].value,'dns.google.');
const html=await server.pageResponse().text(),elements=new Map(),calls=[];
const client=vm.createContext({URL,URLSearchParams,setTimeout,clearTimeout,location:{origin:'https://dns.example',href:'https://dns.example/',search:''},history:{replaceState(){}},document:{getElementById(id){if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',listeners:{},addEventListener(k,f){this.listeners[k]=f;},removeAttribute(k){delete this[k];}});return elements.get(id);}},fetch:async(url,options)=>{assert.equal(new URL(url).searchParams.get('mode'),'ptr');calls.push(JSON.parse(options.body).ips);return server.worker.fetch(new Request(url,options));}});
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],client);
elements.get('domain').value='example.com';await vm.runInContext('runPtrCheck()',client);assert.equal(calls.length,0);
vm.runInContext(`savedAudit={domain:'example.com',hosts:[],data:{checks:['www','mail'].map(n=>({name:n+'.example.com',type:'A',answers:[{ttl:60,value:'8.8.8.8'}]}))}}`,client);
await vm.runInContext('runPtrCheck()',client);assert.equal(calls.length,1);assert.deepEqual(calls[0],['8.8.8.8']);assert.match(elements.get('results').innerHTML,/dns.google/);assert.match(elements.get('results').innerHTML,/www.example.com, mail.example.com/);
await vm.runInContext('runPtrCheck()',client);assert.equal(calls.length,1);
await vm.runInContext('runPtrCheck(true)',client);assert.equal(calls.length,2);
console.log('PASS: IPv4/IPv6 reverse names, invalid input, batch bounds, PTR-only queries, deduplication, scan prerequisite, hostname mapping, cached navigation and explicit refresh.');
